// Dataset for Istanbul Curated Sequential Route (TR, EN, RU)
const routeData = {
  generalTips: {
    tr: {
      istanbulkartTitle: "İstanbulkart & Deniz Ulaşımı (Vapur)",
      istanbulkartBody: "Havalimanından doğrudan Kadıköy'e gitmek için metroda ve şehirdeki tüm toplu taşımalarda (Tramvay, Metro, Vapur) İstanbulkart kullanın. Karaköy veya Beşiktaş'tan Kadıköy'e geçerken mutlaka Vapur'a (vapur turu) binin! Büyüleyici, romantik ve son derece ucuzdur. İstanbulkart uygulamasını indirip QR kod ile kolayca bakiye yükleyebilirsiniz.",
      taxiTitle: "Taksi Uyarısı!",
      taxiBody: "Beşiktaş, Eminönü veya Sultanahmet civarında asla sarı taksi kullanmayın. Bu bölgelerde her zaman yoğun trafik olur. T1 Tramvayı ve Metro çok daha hızlı ve kolaydır. Mutlaka taksi gerekirse sadece Uber kullanın; sarı taksiler kredi kartı kabul etmeyebilir ve sorun çıkarabilir.",
      appLinkText: "İstanbulkart Mobil Uygulamasını İndir"
    },
    en: {
      istanbulkartTitle: "Istanbulkart & Sea Transit (Vapur Ferry)",
      istanbulkartBody: "Use Istanbulkart for all public transit (Metro, Tramway, Ferry) - you can get directly from the airport to Kadikoy via metro. Always take the Vapur (ferry) when crossing between Karakoy/Besiktas and Kadikoy! It's romantic, scenic, easy, and cheap. Download the Istanbulkart app to easily use QR codes and load money with credit card.",
      taxiTitle: "Taxi Warning!",
      taxiBody: "Do NOT take yellow taxis around Besiktas, Eminonu, or Topkapi/Sultanahmet area due to constant heavy traffic. Tramways and metros are much faster. If you must use a taxi, ONLY use Uber; yellow taxis often decline credit cards or overcharge tourists.",
      appLinkText: "Get Istanbulkart Mobile App"
    },
    ru: {
      istanbulkartTitle: "Стамбулкарта и Паромы (Vapur)",
      istanbulkartBody: "Используйте картy Istanbulkart для всего общественного транспорта (метро, трамвай, паром). Из аэропорта можно доехать прямо до Кадыкёя на метро. При переправе между Каракёем/Бешикташем и Кадыкёем обязательно садитесь на паром (Vapur)! Это романтично, живописно и недорого. Скачайте приложение Istanbulkart для пополнения баланса по QR-коду.",
      taxiTitle: "Предупреждение о такси!",
      taxiBody: "НЕ берите желтые такси в районах Бешикташ, Эминёню или Султанахмет из-за постоянных пробок. Трамвай T1 и метро работают гораздо быстрее. Если необходимо такси, используйте ТОЛЬКО Uber.",
      appLinkText: "Скачать приложение Istanbulkart"
    }
  },
  days: {
    tr: {
      tourist: "🏛️ Turist Modu",
      day1: "1. Gün: Fatih & Tarihi Yarımada",
      day2: "2. Gün: Taksim, Pera & Beşiktaş - Boğaz",
      day3: "3. Gün: Anadolu Yakası & Kadıköy Keşfi",
      returning: "🔄 2. & 3. Sefer Gelenler",
      local: "☕ İstanbullu Gibi (Lokal Rota)"
    },
    en: {
      tourist: "🏛️ Tourist Mode",
      day1: "Day 1: Fatih & Historic Peninsula",
      day2: "Day 2: Taksim, Pera & Besiktas - Bosphorus",
      day3: "Day 3: Asian Side & Kadıköy Exploration",
      returning: "🔄 Returning Travelers (2nd/3rd Visit)",
      local: "☕ Feel Like a Local (Local Route)"
    },
    ru: {
      tourist: "🏛️ Туристический режим",
      day1: "День 1: Фатих и Исторический полуостров",
      day2: "День 2: Таксим, Пера и Бешикташ - Босфор",
      day3: "День 3: Азиатская сторона и Кадыкёй",
      returning: "🔄 Для тех, кто в Стамбуле 2-3 раз",
      local: "☕ Стамбул глазами местного"
    }
  },
  locations: [
    // --- DAY 1: EUROPEAN SIDE HISTORIC PENINSULA & KARAKÖY ---
    {
      id: 1,
      day: 1,
      nameTr: "Topkapı Sarayı Müzesi & Harem",
      nameEn: "Topkapi Palace Museum & Harem",
      nameRu: "Музей дворца Топкапы и Гарем",
      category: "historic",
      region: "europe",
      coordinates: [41.0115195, 28.9833789],
      mapsUrl: "https://maps.google.com/?q=Topkapi+Palace+Museum+Istanbul",
      image: "images/topkapi.jpg",
      tipTr: "Osmanlı Sultanlarının yaşadığı en görkemli saray müzesi. Hürrem Sultan'ın da yaşadığı sarayın Harem dairesini mutlaka görün!\n🌳 NOT: Dış bahçelere ve 1. Avluya giriş tamamen ÜCRETSİZDİR.\n🎫 Müze Bilet Ücreti: Yabancı ziyaretçiler için €45 (Topkapı Sarayı + Harem + Aya İrini Karma Bilet).",
      tipEn: "The most important Ottoman palace museum. Must-see: the famous Harem section where Hürrem Sultan lived!\n🌳 NOTE: Entry to outer gardens (Gülhane Park & 1st Courtyard) is FREE!\n🎫 Foreign Visitor Ticket: €45 (Combined Palace + Harem pass).",
      tipRu: "Самый важный музей османского дворца. Обязательно посетите знаменитый Гарем, где жила Хюррем Султан!\n🌳 ПРИМЕЧАНИЕ: Вход во внешние сады — БЕСПЛАТНО!\n🎫 Билет для иностранных туристов: €45 (Дворец + Гарем).",
      transitToNext: {
        type: "walk",
        durationTr: "7-10 dk",
        durationEn: "7-10 mins",
        durationRu: "7-10 мин",
        descTr: "Gülhane Parkı yanından Cağaloğlu/Sirkeci yönüne doğru yürüyün.",
        descEn: "Walk through/past Gulhane Park towards Cagaloglu & Sirkeci.",
        descRu: "Идите через парк Гюльхане в сторону Джагалоглу и Сиркеджи."
      }
    },
    {
      id: 2,
      day: 1,
      nameTr: "Şehzade Cağ Kebap",
      nameEn: "Şehzade Cağ Kebap",
      nameRu: "Şehzade Cağ Kebap",
      category: "food",
      region: "europe",
      coordinates: [41.0139781, 28.9752568],
      mapsUrl: "https://maps.app.goo.gl/hze8JovKihongeYe9",
      image: "images/cag_kebap.jpg",
      tipTr: "Topkapı'ya çok yakın, İstanbul'un en iyi Cağ Kebabı! ÖNEMLİ İPUCU: Kişi başı sadece 2 şiş sipariş edin. Yoğurt, salata teklif ederlerse reddedin, kebaba odaklanın. Doymazsanız yine söylersiniz.",
      tipEn: "Best Cağ Kebab in Istanbul, right near Topkapi! PRO TIP: Order only 2 skewers per person. Decline yogurt/salad extras - focus purely on kebab!",
      tipRu: "Лучший Джаг-кебаб в Стамбуле рядом с Топкапы! СОВЕТ: Заказывайте только 2 шампура на человека. Откажитесь от доп. салатов — сосредоточьтесь на кебабе!",
      transitToNext: {
        type: "walk",
        durationTr: "2 dk",
        durationEn: "2 mins",
        durationRu: "2 мин",
        descTr: "Sirkeci Meydanı tarafındaki tatlıcıya doğru yürüyün.",
        descEn: "Walk just a few steps towards Sirkeci Square dessert shop.",
        descRu: "Пройдите несколько шагов к кондитерской на площади Сиркеджи."
      }
    },
    {
      id: 3,
      day: 1,
      nameTr: "Hafız Mustafa 1864 Sirkeci",
      nameEn: "Hafiz Mustafa 1864 Sirkeci",
      nameRu: "Hafiz Mustafa 1864 Sirkeci",
      category: "food",
      region: "europe",
      coordinates: [41.0146292, 28.9756182],
      mapsUrl: "https://maps.app.goo.gl/kuN6HEYffMAX39sv7",
      image: "images/hafiz_mustafa.jpg",
      tipTr: "Cağ kebaptan sonra Türk çayı ve buranın özel lezzeti 'Ala Trileçe' yemek için mükemmel durak! Ayrıca taze baklavası da meşhurdur.",
      tipEn: "Right after kebab, come here for Turkish tea and their signature 'Ala Trilece' dessert! Fresh baklava is also amazing.",
      tipRu: "Сразу после кебаба зайдите сюда на турецкий чай и фирменный десерт 'Ala Trilece'! Свежая баклава тоже великолепна.",
      transitToNext: {
        type: "walk",
        durationTr: "5 dk",
        durationEn: "5 mins",
        durationRu: "5 мин",
        descTr: "Tramvay caddesinden Sultanahmet Meydanı'na yürüyün.",
        descEn: "Walk along the tram line towards Sultanahmet Square.",
        descRu: "Идите вдоль трамвайной линии в сторону площади Султанахмет."
      }
    },
    {
      id: 4,
      day: 1,
      nameTr: "Ayasofya-i Kebir Cami-i Şerifi",
      nameEn: "Hagia Sophia Grand Mosque",
      nameRu: "Собор Святой Софии (Ая-София)",
      category: "historic",
      region: "europe",
      coordinates: [41.008583, 28.980175],
      mapsUrl: "https://maps.google.com/?q=Hagia+Sophia+Grand+Mosque+Istanbul",
      image: "images/ayasofya.jpg",
      tipTr: "Dünyanın en mimari harikası tarihi yapısı. Kubbesi ve mozaikleri büyüleyicidir.\n🎫 Yabancı Ziyaretçi Bilet Ücreti: €25 (Üst galeri ziyaret alanı).",
      tipEn: "World famous architectural masterpiece. Its dome and mosaics are breathtaking.\n🎫 Foreign Visitor Ticket: €25 (Upper gallery visiting area).",
      tipRu: "Всемирно известный архитектурный шедевр. Вход по билетам. Купол и мозаики завораживают.\n🎫 Билет для иностранных туристов: €25 (Верхняя галерея).",
      transitToNext: {
        type: "walk",
        durationTr: "2 dk",
        durationEn: "2 mins",
        durationRu: "2 мин",
        descTr: "Meydanın hemen karşısındaki Sultanahmet Camii'ne yürüyün.",
        descEn: "Walk right across the square to Blue Mosque.",
        descRu: "Перейдите через площадь к Голубой мечети."
      }
    },
    {
      id: 5,
      day: 1,
      nameTr: "Sultanahmet Camii (Mavi Cami)",
      nameEn: "Sultanahmet Mosque (Blue Mosque)",
      nameRu: "Голубая мечеть (Султанахмет)",
      category: "historic",
      region: "europe",
      coordinates: [41.005400, 28.976800],
      mapsUrl: "https://maps.google.com/?q=Blue+Mosque+Sultanahmet+Istanbul",
      image: "images/sultanahmet.jpg",
      tipTr: "Ayasofya'nın hemen karşısında yükselen 6 minareli muazzam Osmanlı eseri! Mavi İznik çinileriyle meşhurdur.\n🎫 Giriş Ücreti: ÜCRETSİZ (Serbest ziyaret edilebilir).",
      tipEn: "Magnificent 6-minaret Ottoman mosque right across Hagia Sophia! Famous for its blue Iznik tiles.\n🎫 Entry: FREE of charge.",
      tipRu: "Великолепная мечеть с 6 минаретами напротив Ая-Софии! Известна своими синими изникскими изразцами.\n🎫 Вход: БЕСПЛАТНО.",
      transitToNext: {
        type: "walk",
        durationTr: "5 dk",
        durationEn: "5 mins",
        durationRu: "5 мин",
        descTr: "Divanyolu Caddesi boyunca Çemberlitaş yönüne, Çorlulu Ali Paşa Medresesi'ne yürüyün.",
        descEn: "Walk along Divanyolu Street towards Çemberlitaş to Çorlulu Ali Paşa Medrese.",
        descRu: "Идите по улице Диваньолу к медресе Чорлулу Али Паша."
      }
    },
    {
      id: 27,
      day: 1,
      nameTr: "Çorlulu Ali Paşa Medresesi Çay Ocağı",
      nameEn: "Corlulu Ali Pasa Medrese Tea House",
      nameRu: "Медресе Чорлулу Али Паша (Чайхана)",
      category: "food",
      region: "europe",
      coordinates: [41.0089, 28.9684],
      mapsUrl: "https://maps.google.com/?q=Corlulu+Ali+Pasa+Medresesi+Istanbul",
      image: "images/corlulu_alipasa.jpg",
      tipTr: "Tarihi 18. yüzyıl medresesinin otantik avlusunda harika bir ara durak! Sultanahmet ve Ayasofya gezilerinden sonra taze demlenmiş Türk çayı içip dinlenmek için son derece keyifli bir mekandır.",
      tipEn: "An authentic rest stop in the courtyard of an 18th-century historic medrese! Perfect, peaceful spot to relax and enjoy freshly brewed Turkish tea after visiting Sultanahmet & Hagia Sophia.",
      tipRu: "Аутентичная чайхана во дворике исторического медресе 18 века! Идеальное место для отдыха и свежезаваренного турецкого чая.",
      transitToNext: {
        type: "walk",
        durationTr: "3 dk",
        durationEn: "3 mins",
        durationRu: "3 мин",
        descTr: "Beyazıt Meydanı'na doğru yürüyerek İstanbul Üniversitesi Ana Kapısı'nı görün.",
        descEn: "Walk towards Beyazıt Square to see the Istanbul University Main Gate.",
        descRu: "Пройдите к площади Беязыт к главным воротам Стамбульского университета."
      }
    },
    {
      id: 28,
      day: 1,
      nameTr: "İstanbul Üniversitesi Beyazıt Ana Kapısı",
      nameEn: "Istanbul University Main Gate (Beyazıt)",
      nameRu: "Главные ворота Стамбульского университета (Беязыт)",
      category: "historic",
      region: "europe",
      coordinates: [41.0128, 28.9631],
      mapsUrl: "https://maps.google.com/?q=Istanbul+University+Beyazit+Gate",
      image: "images/istanbul_universitesi.jpg",
      tipTr: "Türkiye'nin en köklü ve tarihi üniversitesinin meşhur Beyazıt Meydanı'ndaki görkemli tarihi kapısı. (Canım üniversitem ❤️)",
      tipEn: "The magnificent historic main entrance gate of Turkey's oldest university located at Beyazıt Square. (Canım üniversitem ❤️)",
      tipRu: "Роскошные исторические ворота старейшего университета Турции на площади Беязыт. (Canım üniversitem ❤️)",
      transitToNext: {
        type: "walk",
        durationTr: "2 dk",
        durationEn: "2 mins",
        durationRu: "2 мин",
        descTr: "Meydanın hemen yanındaki Beyazıt/Nuruosmaniye kapısından Kapalıçarşı'ya girin.",
        descEn: "Enter the Grand Bazaar right next to the square via Beyazıt/Nuruosmaniye gate.",
        descRu: "Войдите в Гранд-базар через ворота Беязыт/Нуруосмание прямо рядом с площадью."
      }
    },
    {
      id: 26,
      day: 1,
      nameTr: "Kapalıçarşı (Tarihi Çarşı)",
      nameEn: "Grand Bazaar (Kapalıçarşı)",
      nameRu: "Гранд-базар (Капалы-чарши)",
      category: "historic",
      region: "europe",
      coordinates: [41.0107, 28.9680],
      mapsUrl: "https://maps.google.com/?q=Grand+Bazaar+Istanbul",
      image: "images/kapalicarsi.jpg",
      tipTr: "Dünyanın en eski ve en büyük kapalı çarşılarından biri. ÖNEMLİ İPUCU: Burası esas olarak kuyumcular (altın/takı) ve uygun kurla döviz bozdurmak için idealdir. Mağazalarda pek fazla orijinal ve kaliteli marka ürün bulunmaz, kıyafet/çanta alışverişi için çok tavsiye edilmez.\n🛍️ Giriş Ücreti: ÜCRETSİZ.",
      tipEn: "One of the oldest and largest covered markets in the world. PRO TIP: Mainly ideal for gold/jewelry shops and favorable currency exchange. Note that there aren't really original or high-quality brand items here; not recommended for luxury fashion shopping.\n🛍️ Entry: FREE of charge.",
      tipRu: "Один из старейших и крупнейших крытых рынков в мире. СОВЕТ: В основном идеален для ювелирных магазинов (золото) и выгодного обмена валюты. Заметьте, что оригинальных брендовых вещей высокого качества здесь почти нет.\n🛍️ Вход: БЕСПЛАТНО.",
      transitToNext: {
        type: "walk",
        durationTr: "8-10 dk",
        durationEn: "8-10 mins",
        durationRu: "8-10 мин",
        descTr: "Mahmutpaşa yokuşundan aşağıya doğru Mısır Çarşısı'na (Eminönü) yürüyün.",
        descEn: "Walk down Mahmutpasa slope towards Spice Bazaar (Eminonu).",
        descRu: "Спуститесь по склону Махмутпаша к Египетскому базару (Эминёню)."
      }
    },
    {
      id: 25,
      day: 1,
      nameTr: "Mısır Çarşısı (Tarihi Baharatçılar Çarşısı)",
      nameEn: "Spice Bazaar (Egyptian Bazaar)",
      nameRu: "Египетский базар (Базар специй)",
      category: "historic",
      region: "europe",
      coordinates: [41.0164, 28.9706],
      mapsUrl: "https://maps.google.com/?q=Spice+Bazaar+Istanbul",
      image: "images/misir_carsisi.jpg",
      tipTr: "İstanbul'un en renkli ve mis kokulu tarihi çarşısı. Hediyelik geleneksel Türk lokumu almak için mükemmel bir durak (Özellikle 'Malatya Pazarı' markası favorimizdir!). Rengarenk baharatlar, kuruyemişler ve hediyelikler sunar.\n🛍️ Giriş Ücreti: ÜCRETSİZ.",
      tipEn: "One of Istanbul's most colorful and aromatic historic markets. Perfect spot to buy gift Turkish Delights (Especially the 'Malatya Pazarı' brand is a personal favorite!). Filled with vibrant spices, nuts, teas, and souvenirs.\n🛍️ Entry: FREE of charge.",
      tipRu: "Один из самых ярких и ароматных исторических рынков Стамбула. Отличное место для покупки сувенирного турецкого рахат-лукума (Особенно бренд 'Malatya Pazarı' — наш фаворит!).\n🛍️ Вход: БЕСПЛАТНО.",
      transitToNext: {
        type: "walk",
        durationTr: "8 dk",
        durationEn: "8 mins",
        durationRu: "8 мин",
        descTr: "Galata Köprüsü üzerinden yürüyerek veya 1 durak tramvay ile Karaköy Güllüoğlu'na geçin.",
        descEn: "Walk across Galata Bridge or take T1 tram 1 stop to Karakoy Gulluoglu.",
        descRu: "Пройдите по Галатскому мосту пешком или проедьте 1 остановку на трамвае до Karakoy Gulluoglu."
      }
    },
    {
      id: 6,
      day: 1,
      nameTr: "Karaköy Güllüoğlu Baklava",
      nameEn: "Karakoy Gulluoglu Baklava",
      nameRu: "Karakoy Gulluoglu Baklava",
      category: "food",
      region: "europe",
      coordinates: [41.023250, 28.977200],
      mapsUrl: "https://maps.google.com/?q=Karakoy+Gulluoglu+Baklava+Istanbul",
      image: "images/gulluoglu.jpg",
      tipTr: "Baklavayı icat eden / dünyada baklavanın simgesi olan yer! Türkiye'nin en iyi, en kaliteli ve en havalı baklavacısıdır. Buraya uğramadan İstanbul turu tamamlanmaz.",
      tipEn: "The iconic place that invented / perfected baklava! The coolest and best baklava shop in all of Turkey. Absolutely mandatory stop!",
      tipRu: "Культовое место, где создали лучшую пахлаву! Самая лучшая и стильная кондитерская пахлавы в Турции.",
      transitToNext: null
    },

    // --- DAY 2: TAKSİM, PERA, GALATA, BEŞİKTAŞ & ORTAKÖY ---
    {
      id: 8,
      day: 2,
      nameTr: "Taksim Meydanı & İstiklal Caddesi",
      nameEn: "Taksim Square & Istiklal Avenue",
      nameRu: "Площадь Таксим и улица Истикляль",
      category: "historic",
      region: "europe",
      coordinates: [41.036944, 28.985833],
      mapsUrl: "https://maps.google.com/?q=Taksim+Square+Istiklal+Street+Istanbul",
      image: "images/taksim.jpg",
      tipTr: "2. Gün Başlıyor! İstanbul'un kalbi. Kırmızı nostaljik tramvayın geçtiği, tarihi pasajlar ve mağazalarla dolu hareketli cadde.",
      tipEn: "Day 2 Begins! The beating heart of Istanbul. Bustling pedestrian avenue with the iconic red nostalgic tram and historic passages.",
      tipRu: "День 2 начинается! Сердце Стамбула. Оживленная пешеходная улица со знаменитым красным ностальгическим трамваем.",
      transitToNext: {
        type: "walk",
        durationTr: "5 dk",
        durationEn: "5 mins",
        durationRu: "5 мин",
        descTr: "İstiklal Caddesi üzerindeki Pera Müzesi'ne yürüyün.",
        descEn: "Walk along Istiklal Street to Pera Museum.",
        descRu: "Пройдите по улице Истикляль к музею Пера."
      }
    },
    {
      id: 9,
      day: 2,
      nameTr: "Pera Müzesi (Kaplumbağa Terbiyecisi)",
      nameEn: "Pera Museum (The Tortoise Trainer)",
      nameRu: "Музей Пера (Дрессировщик черепах)",
      category: "historic",
      region: "europe",
      coordinates: [41.031389, 28.975278],
      mapsUrl: "https://maps.google.com/?q=Pera+Museum+Istanbul",
      image: "images/pera_museum.jpg",
      tipTr: "MÜZEYE GİDİLECEKSE EN DOĞRU ADRES! Türk resim sanatının başyapıtı olan Osman Hamdi Bey'in ünlü 'Kaplumbağa Terbiyecisi' tablosu buradadır. Oryantalist anlamda Türkiye'nin en önemli eseridir.\n🎫 Yabancı Ziyaretçi Bilet Ücreti: ~€10.",
      tipEn: "THE MUST-VISIT ART MUSEUM! Home to Osman Hamdi Bey's world-famous masterpiece 'The Tortoise Trainer' - the most important Orientalist painting in Turkish history!\n🎫 Foreign Visitor Ticket: ~€10.",
      tipRu: "ГЛАВНЫЙ ХУДОЖЕСТВЕННЫЙ МУЗЕЙ! Здесь находится шедевр Османа Хамди-бея «Дрессировщик черепах» — самая важная ориенталистская картина в истории Турции!\n🎫 Билет для иностранных туристов: ~€10.",
      transitToNext: {
        type: "walk",
        durationTr: "7 dk",
        durationEn: "7 mins",
        durationRu: "7 мин",
        descTr: "Galata Kulesi yokuşuna doğru yürüyün.",
        descEn: "Walk down towards Galata Tower.",
        descRu: "Спуститесь к башне Галата."
      }
    },
    {
      id: 10,
      day: 2,
      nameTr: "Galata Kulesi",
      nameEn: "Galata Tower",
      nameRu: "Галатская башня",
      category: "historic",
      region: "europe",
      coordinates: [41.0256687, 28.9741792],
      mapsUrl: "https://maps.google.com/?q=Galata+Tower+Istanbul",
      image: "images/galata_tower.jpg",
      tipTr: "İstanbul'un en simgesel tarihi kulesi. En tepesine çıkıp tüm şehri ve Boğazı panoramik olarak izleyin.\n🎫 Yabancı Ziyaretçi Bilet Ücreti: €30.",
      tipEn: "Very old, gorgeous historic tower. Climb to the top for a stunning 360-degree view of Istanbul!\n🎫 Foreign Visitor Ticket: €30.",
      tipRu: "Знаменитая историческая башня. Поднимитесь наверх за панорамным видом на Стамбул!\n🎫 Билет для иностранных туристов: €30.",
      transitToNext: {
        type: "walk",
        durationTr: "1 dk",
        durationEn: "1 min",
        durationRu: "1 мин",
        descTr: "Kulenin hemen altındaki sokağa adım atın.",
        descEn: "Step directly into the street beneath the tower.",
        descRu: "Сделайте несколько шагов на улочку прямо под башней."
      }
    },
    {
      id: 11,
      day: 2,
      nameTr: "Helvacı Ali Galata",
      nameEn: "Helvaci Ali Galata",
      nameRu: "Helvaci Ali Galata",
      category: "food",
      region: "europe",
      coordinates: [41.027199, 28.972190],
      mapsUrl: "https://maps.app.goo.gl/yxyBddx4Y41u17no9",
      image: "images/helvaci_ali.jpg",
      tipTr: "Kuleyi gezdikten sonra mutlaka Antep fıstıklı sıcak dondurmalı helvasını deneyin! En sevilen lezzet duraklarından biridir.",
      tipEn: "Must-try warm pistachio helva over ice cream near Galata tower! Local favorite sweet treat.",
      tipRu: "Попробуйте теплую фисташковую хельву с мороженым около башни Галата!",
      transitToNext: {
        type: "metro",
        durationTr: "12 dk",
        durationEn: "12 mins",
        durationRu: "12 мин",
        descTr: "Şişhane'den M2 Metro veya otobüs ile Beşiktaş / Dolmabahçe Sarayı yönüne geçin.",
        descEn: "Take M2 Metro from Şişhane or bus to Besiktas / Dolmabahce Palace.",
        descRu: "На метро M2 от Шишхане или на автобусе доедьте до Бешикташа / Долмабахче."
      }
    },
    {
      id: 12,
      day: 2,
      nameTr: "Dolmabahçe Sarayı Müzesi & Saat Kule Kafeterya",
      nameEn: "Dolmabahce Palace & Clock Tower Cafe",
      nameRu: "Дворец Долмабахче и Кафе у Часовой башни",
      category: "historic",
      region: "europe",
      coordinates: [41.0376471, 28.9968587],
      mapsUrl: "https://maps.google.com/?q=Dolmabahce+Palace+Istanbul",
      image: "images/dolmabahce.jpg",
      tipTr: "Son Osmanlı sarayı. Gezmeye vaktiniz olmasa dahi deniz kıyısındaki Saat Kule Kafeteryasında oturup Boğaz'ı seyredin.\n🎫 Yabancı Ziyaretçi Bilet Ücreti: €30 (Selamlık + Harem Tam Bilet).",
      tipEn: "The grand last Ottoman palace. If short on time, relax at Saat Kule Cafe right on the Bosphorus shoreline.\n🎫 Foreign Visitor Ticket: €30 (Full Palace + Harem pass).",
      tipRu: "Роскошный последний дворец османов. Отдохните в кафе у Часовой башни прямо у пролива Босфор.\n🎫 Билет для иностранных туристов: €30 (Дворец + Гарем).",
      transitToNext: {
        type: "walk",
        durationTr: "10 dk",
        durationEn: "10 mins",
        durationRu: "10 мин",
        descTr: "Beşiktaş Meydanı ve Çarşısı içine doğru yürüyün.",
        descEn: "Stroll towards Besiktas Square and inner bazaar.",
        descRu: "Прогуляйтесь к площади Бешикташ и местному базарчику."
      }
    },
    {
      id: 13,
      day: 2,
      nameTr: "Balkanlar Lokantası (Beşiktaş)",
      nameEn: "Balkanlar Lokantasi (Beşiktaş)",
      nameRu: "Balkanlar Lokantasi (Бешикташ)",
      category: "food",
      region: "europe",
      coordinates: [41.041800, 29.002800],
      mapsUrl: "https://maps.google.com/?q=Balkanlar+Lokantasi+Besiktas+Istanbul",
      image: "images/balkanlar.jpg",
      tipTr: "Beşiktaş Çarşısı'nda çok uygun fiyatlı ve harika lezzette Türk ev yemekleri sunan geleneksel lokanta.",
      tipEn: "Incredibly cheap yet high-quality authentic Turkish home-cooked dishes in Beşiktaş.",
      tipRu: "Недорогой и очень вкусный ресторан домашней турецкой кухни в Бешикташе.",
      transitToNext: {
        type: "walk",
        durationTr: "10 dk",
        durationEn: "10 mins",
        durationRu: "10 мин",
        descTr: "Ortaköy yönüne sahil boyunca yürüyün veya 1 durak otobüse binin.",
        descEn: "Walk along the coast to Ortakoy or take a short bus.",
        descRu: "Прогуляйтесь вдоль побережья в Ортакёй или проедьте 1 остановку."
      }
    },
    {
      id: 15,
      day: 2,
      nameTr: "Ortaköy Meydanı & Camii",
      nameEn: "Ortakoy Square & Bosphorus View",
      nameRu: "Площадь Ортакёй и виды на Босфор",
      category: "historic",
      region: "europe",
      coordinates: [41.0475105, 29.0258132],
      mapsUrl: "https://maps.google.com/?q=Ortakoy+Square+Istanbul",
      image: "images/ortakoy.jpg",
      tipTr: "Boğaz Köprüsü altında eşsiz manzara! Buradan Beşiktaş veya Karaköy iskelesine geçerek Kadıköy Vapuruna binin.",
      tipEn: "Famous scenic spot right under the Bosphorus Bridge. From here, head to ferry pier for Kadıköy boat ride.",
      tipRu: "Живописное место прямо под Босфорским мостом. Отсюда можно отправиться на паром до Кадыкёя.",
      transitToNext: null
    },

    // --- DAY 3: ASIAN SIDE & KADIKÖY DISCOVERY ---
    {
      id: 16,
      day: 3,
      nameTr: "Kadıköy Boğa Heykeli",
      nameEn: "Kadikoy Bull Statue",
      nameRu: "Бык в Кадыкёе (Boğa Heykeli)",
      category: "historic",
      region: "asia",
      coordinates: [40.990421, 29.0291723],
      mapsUrl: "https://maps.google.com/?q=Kadikoy+Boga+Heykeli+Istanbul",
      image: "images/kadikoy_boga.jpg",
      tipTr: "3. Gün Başlıyor! Kadıköy'ün en ikonik buluşma noktası. Önünde hatıra fotoğrafı çektirmek gelenektir.",
      tipEn: "Day 3 Begins! Signature meeting landmark of Kadikoy. Take a landmark photo in front of the bronze bull!",
      tipRu: "День 3 начинается! Самый знаменитый ориентир Кадыкёя. Сделайте фото у бронзового быка!",
      transitToNext: {
        type: "walk",
        durationTr: "3 dk",
        durationEn: "3 mins",
        durationRu: "3 мин",
        descTr: "Kahvaltı mekanlarına doğru yürüyün.",
        descEn: "Walk towards the breakfast spots.",
        descRu: "Пройдите к кафе для завтрака."
      }
    },
    {
      id: 17,
      day: 3,
      nameTr: "Luşnika Cafe (Kadıköy Kahvaltı Durağı)",
      nameEn: "Luşnika Cafe (Kadikoy Breakfast Spot)",
      nameRu: "Luşnika Cafe (Завтрак в Кадыкёе)",
      category: "food",
      region: "asia",
      coordinates: [40.990277, 29.025690],
      mapsUrl: "https://maps.google.com/?q=Lusnika+Cafe+Kadikoy",
      image: "images/kadikoy_breakfast.jpg",
      tipTr: "Zengin Serpme Türk Kahvaltısı için son derece uygun fiyatlı ve kaliteli bir adres.",
      tipEn: "An excellent, budget-friendly and high-quality spot for a rich traditional Turkish Breakfast.",
      tipRu: "Отличное, доступное и качественное место для традиционного турецкого завтрака.",
      transitToNext: {
        type: "walk",
        durationTr: "4 dk",
        durationEn: "4 mins",
        durationRu: "4 мин",
        descTr: "Tatar Salim Dönerci'ye doğru yürüyün.",
        descEn: "Walk over to Tatar Salim Doner.",
        descRu: "Идите к донерной Tatar Salim."
      }
    },
    {
      id: 18,
      day: 3,
      nameTr: "Tatar Salim Döner (Kadıköy)",
      nameEn: "Tatar Salim Doner (Kadikoy)",
      nameRu: "Tatar Salim Doner (Кадыкёй)",
      category: "food",
      region: "asia",
      coordinates: [40.988500, 29.027800],
      mapsUrl: "https://maps.google.com/?q=Tatar+Salim+Doner+Kadikoy+Istanbul",
      image: "images/tatar_salim.jpg",
      tipTr: "MÜKEMMEL DÖNER DURAĞI! İstanbul'un tartışmasız EN İYİ DÖNERCİSİ. Gerçek yaprak et döneri burada yemelisiniz.",
      tipEn: "THE BEST DONER KEBAB IN ISTANBUL! Authentic premium leaf meat doner. Absolutely world-class quality!",
      tipRu: "ЛУЧШИЙ ДОНЕР В СТАМБУЛЕ! Настоящий премиальный мясной донер. Обязательно попробуйте!",
      transitToNext: {
        type: "walk",
        durationTr: "3 dk",
        durationEn: "3 mins",
        durationRu: "3 мин",
        descTr: "Tarihi Kadıköy Çarşısı içindeki Yanyalı Fehmi Lokantası'na geçin.",
        descEn: "Walk into Kadikoy Bazaar to Yanyali Fehmi.",
        descRu: "Зайдите на рынок Кадыкёй к Yanyali Fehmi."
      }
    },
    {
      id: 19,
      day: 3,
      nameTr: "Yanyalı Fehmi Lokantası",
      nameEn: "Yanyali Fehmi Lokantasi",
      nameRu: "Yanyali Fehmi Lokantasi",
      category: "food",
      region: "asia",
      coordinates: [40.9907688, 29.0255674],
      mapsUrl: "https://maps.app.goo.gl/852a787003a6d728",
      image: "images/yanyali_fehmi.jpg",
      tipTr: "Tarihi Kadıköy Çarşısı'nın tam içinde yer alır. Biraz pahalıdır ama ÇOK KALİTELİ geleneksel Türk ve Osmanlı ev yemekleri sunar. Yemeğin üstüne çay ile fırın Sütlaç yemelisiniz!",
      tipEn: "Located right inside Kadikoy Bazaar. A bit pricey, but VERY HIGH QUALITY Ottoman & Turkish home cooking. Try their baked Sütlaç dessert with tea!",
      tipRu: "Прямо на рынке Кадыкёй. Немного дорого, но ОЧЕНЬ КАЧЕСТВЕННАЯ османская домашняя кухня. Попробуйте рисовый пудинг Сютлач!",
      transitToNext: {
        type: "walk",
        durationTr: "2 dk",
        durationEn: "2 mins",
        durationRu: "2 мин",
        descTr: "Çarşı içindeki Kadıköy Midyecisi'ne yürüyün.",
        descEn: "Walk a few steps to Kadikoy Midyecisi.",
        descRu: "Пройдите пару шагов к Kadikoy Midyecisi."
      }
    },
    {
      id: 20,
      day: 3,
      nameTr: "Kadıköy Midyecisi",
      nameEn: "Kadikoy Midyecisi",
      nameRu: "Kadikoy Midyecisi",
      category: "food",
      region: "asia",
      coordinates: [40.9880334, 29.0242096],
      mapsUrl: "https://maps.google.com/?q=Kadikoy+Midyecisi+Istanbul",
      image: "images/kadikoy_midye.jpg",
      tipTr: "Anadolu yakasında midye dolma durağı. Gitmek ÇOK ŞART DEĞİL, ama midye seviyorsanız yine de denenebilir.",
      tipEn: "Midye dolma option on Asian side. NOT MANDATORY, but a good quick stop if you enjoy stuffed mussels.",
      tipRu: "Мидии в Кадыкёе. НЕ обязательно, но можно зайти, если любите фаршированные мидии.",
      transitToNext: {
        type: "walk",
        durationTr: "3 dk",
        durationEn: "3 mins",
        durationRu: "3 мин",
        descTr: "Kadıköy geleneksel meyhaneler sokağına yürüyün.",
        descEn: "Walk towards the traditional tavernas street.",
        descRu: "Идите к улице традиционных таверн."
      }
    },
    {
      id: 22,
      day: 3,
      nameTr: "Güneşin Sofrası Meyhane",
      nameEn: "Gunesin Sofrasi Traditional Taverna",
      nameRu: "Таверна Gunesin Sofrasi",
      category: "nightlife",
      region: "asia",
      coordinates: [40.9898532, 29.0301897],
      mapsUrl: "https://maps.google.com/?q=Gunesin+Sofrasi+Meyhane+Kadikoy",
      image: "images/gunesin_sofrasi.jpg",
      tipTr: "Kadıköy'deki en sevdiğim geleneksel Türk Meyhanesi! Mezeleri harikadır. Cumartesi akşamları dolu olabilir.",
      tipEn: "My favorite traditional Turkish Meyhane (taverna) in Kadikoy! Fantastic cold & warm mezes.",
      tipRu: "Моя любимая традиционная турецкая мейхане (таверна) в Кадыкёе! Отличные закуски мезе.",
      transitToNext: {
        type: "walk",
        durationTr: "2 dk",
        durationEn: "2 mins",
        durationRu: "2 мин",
        descTr: "Barlar sokağındaki Kuzen Sahne'ye yürüyün.",
        descEn: "Walk to Kuzen Sahne in the cellar.",
        descRu: "Пройдите в Kuzen Sahne в подвале."
      }
    },
    {
      id: 23,
      day: 3,
      nameTr: "Kuzen Beer Cafe / Kuzen Sahne",
      nameEn: "Kuzen Beer Cafe (Live Music Cellar)",
      nameRu: "Kuzen Beer Cafe (Живая музыка)",
      category: "nightlife",
      region: "asia",
      coordinates: [40.988888, 29.0244319],
      mapsUrl: "https://maps.google.com/?q=Kuzen+Beer+Cafe+Kadikoy",
      image: "images/kuzen_bar.jpg",
      tipTr: "Mahzen katındaki harika atmosferi, canlı grup performansları ve bira çeşitleriyle Kadıköy gecelerinin vazgeçilmezi.",
      tipEn: "Awesome cellar vibe featuring live band performances and great draft beer selection.",
      tipRu: "Отличный подвальный бар с живой музыкой и большим выбором пива.",
      transitToNext: {
        type: "walk",
        durationTr: "3 dk",
        durationEn: "3 mins",
        durationRu: "3 мин",
        descTr: "Fül Fül Çorba mekanına doğru yürüyün.",
        descEn: "Walk to Fül Fül Çorba.",
        descRu: "Пройдите к Fül Fül Çorba."
      }
    },
    {
      id: 24,
      day: 3,
      nameTr: "Fül Fül Çorba",
      nameEn: "Ful Ful Corba (Soup Experience)",
      nameRu: "Ful Ful Corba (Супный опыт)",
      category: "food",
      region: "asia",
      coordinates: [40.993864, 29.036384],
      mapsUrl: "https://maps.google.com/?q=Ful+Ful+Corba+Kadikoy",
      image: "images/ful_ful.jpg",
      tipTr: "GELENEKSEL DENEYİM MEKANI! Farklı Türk çorba çeşitlerini tadabileceğiniz harika bir kültür deneyim mekanıdır.",
      tipEn: "A TRULY UNIQUE EXPERIENCE VENUE! Great place to sample authentic diverse Turkish soup varieties.",
      tipRu: "УНИКАЛЬНОЕ МЕСТО ДЛЯ КУЛИНАРНОГО ОПЫТА! Отличный шанс попробовать разные виды традиционных турецких супов.",
      transitToNext: null
    }
  ]
};
